version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    environment:
      - ENV=development

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge

volumes:
  data:
  logs: